### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by aferust** [gilzoide/betterclist#1]
Hey, I have just seen your works and wanted to share some of my libraries that can be potentially used in games.

https://github.com/aferust/dvector similar to betterclist
https://github.com/aferust/bcaa AA in betterC
https://github.com/aferust/earcut-d d port of [earcut](https://github.com/mapbox/earcut.hpp)

this is my hobby [game ](https://github.com/aferust/drawee-wasm) that uses my dvector and earcut-d. I am a beginner with OpenGL stuff, probably I did stupid things with rendering.

playable game is here:
https://aferust.github.io/drawee-wasm/ 

Thank you for contributing to d world!

**Comment by gilzoide** [comment]
Hi there @aferust!

Thanks for sharing your work, I'm really enjoying D (well, there are some annoyances, but it's mostly awesome) and would like to be more involved with the community ^^
I liked `drawee`,  although I had to find [this repository](https://github.com/aferust/drawee) for learning the controls, maybe you could `writeln` or `printf` them so that people coming directly to the playable page know how to play.

I actually checked both `dvector` and `bcaa` before starting implementing a new library, they are very nice, although didn't quite fit what I was looking for. I have not used `dvector` mostly because I wanted static memory management (my crazy [experimental game's engine](https://github.com/gilzoide/d-sokol-game) is based on objects/scenes being nested structs/arrays/data).

I will upload more of my libraries to DUB, but I want to add a little documentation to them first  =X

If you like, we can discuss more about D, betterC, game development, OpenGL or whatever, just email me about it!

Thanks again, all the best for you!

**Comment by aferust** [comment]
Ah yes, I should have included some instructions about controls. In the first version, I used legacy OpenGL functions, then I tried to work it on the web using emscripten. Emscripten has no good support for legacy opengl, so I tried to use modern opengl. I have near-zero experience in both. For instance, enemies and the hero has elliptic shapes, which is not my intended behaviour, they should be circles. I understand that I need some orthogonal translations doing some matrix math potentially using your bettercmath. So, it is my hobby game helping me understanding some basics. Additionally, when the [druntime work](https://github.com/skoppe/druntime/tree/wasm) (for wasm) of Sebastiaan is complete, I, hopefully, will not need betterC for the web though.

**Comment by gilzoide** [comment]
Oh, I understand.

For simple 2D shapes like that, you can use [SDL2's hardware accelerated 2D rendering API](https://wiki.libsdl.org/CategoryRender), unless your goal is to learn OpenGL.

For the circle distortion, it's best to just use an orthogonal projection matrix that matches the screen aspect ratio in your shaders and do your game math thinking in absolute position instead of screen position, without having to `translateX` and `translateY` values.
This way, you just multiply this matrix by your position vector like `gl_Position = projection_matrix * vec4(position.xyz, 1.0);` and everything is translated/scaled to the right places in the screen.
You can hardcode a matrix as [glOrtho](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml) would create or create one in CPU and bind it as uniform.

`bettercmath` does have orthogonal/perspective matrix constructors, but you only need to create them once and bind to your shaders, all other math for positions and stuff you can maintain the way it is if you want ^^
Of course, the library has other functionality that may help, feel free to use it! (I will upload it to DUB like today)

If you want, you can also just create circle and rectangle vertices once and pass their center position as a uniform to the shaders.
This way you can create a single circle and a single rectangle centered at the origin (0, 0), and just rebind the position uniform before drawing each of them.
The same applies to the objects' colors, this way you could have just one shader =]

As a C developer, I find myself pretty comfortable using betterC, it's just annoying when libraries, including Phobos, have some sort of TypeInfo or Exception usage and don't compile =/

**Comment by aferust** [comment]
Dear Barbosa,

Thank you for your reply. I need to rotate the enemies around
custom-defined axes which are their center of mass. Although it is not
implemented, can I use any workaround?

this is the shader code:
https://github.com/aferust/drawee/blob/master/source/primitives.d#L710

This is the beginning of the code block supposed to make required transform.
https://github.com/aferust/drawee/blob/master/source/primitives.d#L379

Thank you
